name       : widelands
version    : 19
release    : 3
source     :
    - https://launchpadlibrarian.net/292884200/widelands-build19-src.tar.bz2 : e511f9d26828a2b71b64cdfc6674e6e847543b2da73961ab882acca36c7c01a6
license    : GPL-2.0
component  : games.strategy
summary    : Widelands is a free, open source real-time strategy game with singleplayer
    campaigns and a multiplayer mode
description: |
    Widelands is a free, open source real-time strategy game with singleplayer campaigns and a multiplayer mode
builddeps  :
    - pkgconfig(glew)
    - pkgconfig(harfbuzz)
    - pkgconfig(icu-i18n)
    - pkgconfig(libpng)
    - pkgconfig(SDL2_image)
    - pkgconfig(SDL2_mixer)
    - pkgconfig(SDL2_net)
    - pkgconfig(SDL2_ttf)
    - libboost-devel
setup      : |
    mkdir build
    cd build
    %cmake -DCMAKE_BUILD_TYPE=Release \
           -DCMAKE_INSTALL_PREFIX=/usr/bin \
           -DWL_INSTALL_BASEDIR=/usr/share/widelands \
           -DWL_INSTALL_DATADIR=/usr/share/widelands \
           ..
build      : |
    cd build
    %make
install    : |
    cd build
    %make_install
    install -D -m 00644 $pkgfiles/widelands.desktop $installdir/usr/share/applications/widelands.desktop
    install -D -m 00644 $pkgfiles/widelands.png $installdir/usr/share/pixmaps/widelands.png
