name       : widelands
version    : 19
release    : 15
source     :
    - https://launchpad.net/widelands/build19/build19/+download/widelands-build19-src-gcc7.tar.bz2 : ef73b8cf5a7c680bad5caade907f1cc6ee88dd3729470b9214a3c72658585458
license    : GPL-2.0-or-later
component  : games.strategy
summary    : Widelands is a free, open source real-time strategy game with singleplayer
    campaigns and a multiplayer mode
description: |
    Widelands is a free, open source real-time strategy game with singleplayer campaigns and a multiplayer mode
builddeps  :
    - pkgconfig(glew)
    - pkgconfig(harfbuzz)
    - pkgconfig(icu-i18n)
    - pkgconfig(libpng)
    - pkgconfig(SDL2_image)
    - pkgconfig(SDL2_mixer)
    - pkgconfig(SDL2_net)
    - pkgconfig(SDL2_ttf)
    - libboost-devel
setup      : |
    # http://site.icu-project.org/download/61#TOC-Migration-Issues
    export CXXFLAGS+=' -DU_USING_ICU_NAMESPACE=1'

    mkdir build && cd build
    %cmake -DCMAKE_BUILD_TYPE=Release \
           -DCMAKE_INSTALL_PREFIX=/usr/bin \
           -DWL_INSTALL_BASEDIR=/usr/share/widelands \
           -DWL_INSTALL_DATADIR=/usr/share/widelands \
           ..
build      : |
    %make -C build
install    : |
    %make_install -C build
    install -D -m 00644 $pkgfiles/widelands.desktop $installdir/usr/share/applications/widelands.desktop
    install -D -m 00644 $pkgfiles/widelands.png $installdir/usr/share/pixmaps/widelands.png
