name       : widelands
version    : '1.0'
release    : 23
source     :
    - https://github.com/widelands/widelands/archive/refs/tags/v1.0.tar.gz : 1dab0c4062873cc72c5e0558f9e9620b0ef185f1a78923a77c4ce5b9ed76031a
license    : GPL-2.0-or-later
component  : games.strategy
summary    : Widelands is a free, open source real-time strategy game with singleplayer campaigns and a multiplayer mode
description: |
    Widelands is a free, open source real-time strategy game with singleplayer campaigns and a multiplayer mode.
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(glew)
    - pkgconfig(harfbuzz)
    - pkgconfig(icu-i18n)
    - pkgconfig(libpng)
    - pkgconfig(SDL2_image)
    - pkgconfig(SDL2_mixer)
    - pkgconfig(SDL2_ttf)
    - dejavu-fonts-ttf
    - libboost-devel
environment: |
    export GCC_IGNORE_WERROR=1
setup      : |
    # http://site.icu-project.org/download/61#TOC-Migration-Issues
    export CXXFLAGS+=' -DU_USING_ICU_NAMESPACE=1'

    %patch -p1 < $pkgfiles/missing-include.patch
    %patch -p1 < $pkgfiles/0001-fucking-cunts.patch

    mkdir build && cd build
    %cmake -DCMAKE_BUILD_TYPE=Release \
           -DCMAKE_INSTALL_PREFIX=/usr/bin \
           -DWL_INSTALL_BASEDIR=/usr/share/widelands \
           -DWL_INSTALL_DATADIR=/usr/share/widelands \
           -DWL_COMPILE_DIAGNOSTICS="-Wno-error" \
           ..
build      : |
    %make -C build
install    : |
    %make_install -C build
    #install -D -m 00644 $pkgfiles/widelands.desktop $installdir/usr/share/applications/widelands.desktop
    #install -D -m 00644 $pkgfiles/widelands.png $installdir/usr/share/pixmaps/widelands.png
